# Everything you wanted to know about exceptions
>   Error handling is just part of life when it comes to writing code.
    We can often check and validate conditions for expected behavior.
    When the unexpected happens, we turn to exception handling.
    You can easily handle exceptions generated by other people's code
    or you can generate your own exceptions for others to handle.

## Exception
>   An Exception is like an event that is created
    when normal error handling can't deal with the issue.
    Trying to divide a number by zero or running out of memory are
    examples of something that creates an exception.

## Throw and Catch
>   When an exception happens, we say that an exception is thrown.
    To handle a thrown exception, you need to catch it.
    If an exception is thrown and it isn't caught by something, the script stops executing.

## The call stack
>   The call stack is the list of functions that have called each other.
    When a function is called, it gets added to the stack or the top of the list.
    When the function exits or returns, it is removed from the stack.

+   When an exception is thrown, that call stack is checked in order for an exception handler to catch it.

## Terminating and non-terminating errors
>   An exception is generally a terminating error. A thrown exception is either be caught
    or it terminates the current execution. 
    By default, a non-terminating error is generated by `Write-Error`
    and it adds an error to the output stream without throwing an exception.

+   I point this out because `Write-Error` and other non-terminating errors do not trigger the `catch`.

## Swallowing an exception
+   This is when you catch an error just to suppress it.
    Do this with caution because it can make troubleshooting issues very difficult.

# Basic command syntax
## Throw
+ To create our own exception event, we throw an exception with the `throw` keyword.
```ps1
    function Start-Something
    {
        throw "Bad thing happened"
    }
```
_This creates a runtime exception that is a terminating error.
It's handled by a `catch` in a calling function or exits the script with a message like this._
```ps1
    PS> Start-Something

    Bad thing happened
    At line:1 char:1
    + throw "Bad thing happened"
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : OperationStopped: (Bad thing happened:String) [], RuntimeException
        + FullyQualifiedErrorId : Bad thing happened
```

## Write-Error -ErrorAction Stop
>   I mentioned that `Write-Error` doesn't throw a terminating error by default.
    If you specify -ErrorAction Stop, `Write-Error` generates a terminating error that can be handled with a catch.
```ps1
    Write-Error -Message "Houston, we have a problem." -ErrorAction Stop
```

## Cmdlet -ErrorAction Stop
>   If you specify `-ErrorAction` Stop on any advanced function or cmdlet,
    it turns all `Write-Error` statements into terminating errors
    that stop execution or that can be handled by a `catch`.
```ps1
    Start-Something -ErrorAction Stop
```

## Try/Catch
```ps1
    try
    {
        Start-Something
    }
    catch
    {
        Write-Output "Something threw an exception"
        Write-Output $_
    }

    try
    {
        Start-Something -ErrorAction Stop
    }
    catch
    {
        Write-Output "Something threw an exception or used Write-Error"
        Write-Output $_
    }
```
+ The `catch` script only runs if there's a terminating error.
  If the try executes correctly, then it skips over the `catch`.
  You can access the exception information in the `catch` block using the `$_` variable.

## Try/Finally







